### PR TITLE
Fix port in error message

### PR DESCRIPTION
**Pull request by daniloakamine**
Port 9090 is not a default port to "auth_host_port" argument.
Should be 8090 instead of 9090.

### CODE REVIEW

**Comment by dhermes** [comment]
LGTM, but can't merge until the CLA is signed

**Comment by daniloakamine** [comment]
I signed it!

**Comment by dhermes** [comment]
So it looks like @daniloakamine-luizalabs is the commit author.

**Comment by daniloakamine** [comment]
well, I will open a new PR, my username was wrong :(

**Comment by dhermes** [comment]
GitHub is basing the username on the email address on the commit message.

**Comment by daniloakamine** [comment]
Done! email now is OK!

**Comment by daniloakamine** [comment]
thanks @dhermes :+1:

**Pull request merged**
