### PR TITLE
Remove all uses of MagicMock

### PR DESCRIPTION
**Pull request by dhermes**
`MagicMock` is a version of `Mock` with extra features for tests that need to test usage of magic methods (i.e. `__nonzero__`, `__cmp__`, etc.).

None of the `oauth2client` tests actually need these extra features though.

### CODE REVIEW

**Comment by dhermes** [comment]
It seems py33 has started failing because of `django`. FWIW `django` [dropped support][1] for 3.3 on Dec. 1, 2015.

The `gcloud-python` project has also stopped supporting 3.3

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/issues/995#issuecomment-168126798

**Comment by jonparrott** [comment]
We might as well drop 3.3 as well. This LGTM, the travis failure should be addressed separately.

**Comment by nathanielmanistaatgoogle** [comment]
Commit itself looks fine; will this not get a passing build until 3.3 support is dropped?

**Comment by jonparrott** [comment]
@nathanielmanistaatgoogle correct. I'll try to do that today (dealing with a product launch).

**Comment by dhermes** [comment]
TADA! I just made #604

**Pull request merged**
