### PR TITLE
Foo

### PR DESCRIPTION
**Pull request by dhermes**
@nathanielmanistaatgoogle @craigcitro This is to test which environment variables are actually set (without printing their values).

I already am tracking this in https://github.com/GoogleCloudPlatform/gcloud-python/issues/874 and get

```
$ python -c "import os; print '\n'.join(os.environ.keys())"
_
SHLVL
VIRTUAL_ENV
PWD
PYTHONHASHSEED
PATH
```

even though the [Travis docs](http://docs.travis-ci.com/user/ci-environment/) say all of

```
TRAVIS=true
TRAVIS_BRANCH
TRAVIS_BUILD_DIR
TRAVIS_BUILD_ID
TRAVIS_BUILD_NUMBER
TRAVIS_COMMIT
TRAVIS_COMMIT_RANGE
TRAVIS_JOB_ID
TRAVIS_JOB_NUMBER
TRAVIS_PULL_REQUEST
TRAVIS_SECURE_ENV_VARS
TRAVIS_REPO_SLUG
TRAVIS_OS_NAME
TRAVIS_TAG
```

should be set.

### CODE REVIEW

**Comment by craigcitro** [comment]
have you looked at their twitter account to see if this is a known issue?

i can hop in the slack channel shortly to ask if need be ...

**Comment by dhermes** [comment]
No mention of it on Twitter. I also did a search for "travis environment variables" and searched https://github.com/travis-ci/travis-ci/issues

**Comment by dhermes** [comment]
It seems @tseaver has [found][1] the issue. It's `tox`.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/issues/874#issuecomment-101762459

**Comment by tseaver** [comment]
`tox.ini` needs a `passenv =` element in the relevant testenv stanzas, similar to https://github.com/GoogleCloudPlatform/gcloud-python/pull/875

**Pull request closed without merging**
