### PR TITLE
Updated Google URIs

### PR DESCRIPTION
**Pull request by jay0lee**
GOOGLE_AUTH_URI update as documented at:
https://developers.google.com/identity/protocols/OAuth2UserAgent#formingtheurl

GOOGLE_TOKEN_URI update as documented at:
https://developers.google.com/identity/protocols/OAuth2InstalledApp#handlingtheresponse

GOOGLE_TOKEN_INFO_URI update as documented at:
https://developers.google.com/identity/protocols/OAuth2UserAgent#tokeninfo-validation

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
@jay0lee: please merge commits. There's no need for this change to be spread across three commits.

@aeijdenberg: would you be comfortable reviewing the content of this change? It's quite small.

**Comment by aeijdenberg** [comment]
Hi Nathaniel, I wasn't actually aware that the OAuth endpoint version numbers had been bumped (I'm no longer working in that area).  anthm@ might be a better choice to review?

**Comment by anthmgoogle** [comment]
I was also not aware of these revisions. But since this is bringing it up to date with public documentation this Looks Good To Me. 

Before merging, can you make sure the new endpoints work with the library by exercising some example code?

**Comment by dhermes** [comment]
This is why `tox -e system-tests` exists :grinning: 

@anthmgoogle The Travis merge build will also fail if it isn't valid

**Comment by nathanielmanistaatgoogle** [comment]
@jay0lee: please squash commits?

**Comment by jay0lee** [comment]
Sorry for delay, commits are squashed now.

**Pull request merged**
