### PR TITLE
Removing SignedJwtAssertionCredentials.

### PR DESCRIPTION
**Pull request by nathanielmanistaatgoogle**
This is #399 with `tests/test__pycrypto_crypt.py` changed to use `unittest2`.

### CODE REVIEW

**Comment by dhermes** [comment]
LGTM, though I meant to update the `s` to `json_str` change actually be `json_data` (based on #396 or #397)

**Comment by nathanielmanistaatgoogle** [comment]
I can change `json_str` to `json_data`.

Any idea why the tests haven't yet kicked off for this?

**Comment by nathanielmanistaatgoogle** [comment]
@googlebot you're being silly and failing to recognize an authored-by-@dhermes-committed-by-@nathanielmanistaatgoogle commit as legitimate to merge.

**Comment by dhermes** [comment]
1. ISTM the `google` org gets rate limited (also having 8 Travis envs probably doesn't help)
1. I've had the CLA check fail like this before. I think it's a corner case the server isn't implemented to handle?

**Comment by nathanielmanistaatgoogle** [comment]
Changed `json_str` to `json_data` in `oauth2client/client.py`; please take another quick look.

Any way to poke Travis to make it notice that a different commit has been pushed? I cancelled the test run of 81da3192423237b6.

**Comment by dhermes** [comment]
You've gotta figure out what the rate limit is. Need to check with whoever owns the org

**Comment by dhermes** [comment]
Still LGTM

**Pull request merged**
