### PR TITLE
Getting to 100% coverage for gce module.

### PR DESCRIPTION
**Pull request by dhermes**

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
Python 3 Travis tests aren't happy. :-(

**Comment by dhermes** [comment]
OK If I do it one more time I need a time out

**Comment by dhermes** [comment]
OK that is a pretty serious change in behavior in Python3: http://stackoverflow.com/q/29268892/1068170

Scary!

----

Anyhow, I fixed it and `push --force`d the PR with the working code.

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle Tests passing now (sorry for acting like a n00b contributor)

**Pull request merged**
