### PR TITLE
Add branch coverage

### LINKED ISSUE #611: Does py.test have branch coverage
@pferate Can you chime in here? It seems the `sqlalchemy` branch miss has been fixed without being fixed and I don't see anything in the coverage report about branches.

### PR DESCRIPTION
**Pull request by pferate**
It was unintentionally dropped during the migration to pytest.

Resolves #611

### CODE REVIEW

**Comment by dhermes** [comment]
Ha! I love how easy that was.

I'll wait for @nathanielmanistaatgoogle / @jonparrott to chime on before merging, but it should be pretty simple.

**Comment by pferate** [comment]
Nose had a `--cover-branches` flag, so I was looking for something similar, but couldn't find anything.  Then I saw that config in the `pytest-cov` repo and thought "it can't be _that_ simple, can it?"

**Comment by jonparrott** [comment]
LGTM, merging once the test god is happy.

**Comment by dhermes** [comment]
w00t, the branch misses in `sqlalchemy` showed back up

```
oauth2client/contrib/sqlalchemy.py                     34      0      6      2    95%   148->150, 164->167
```

so `py.test` is working, but coveralls.io still doesn't support branch coverage.

@jonparrott is there a way to inspect the coverage report for branch coverage and then add a mock failed coverage if there is a branch miss?

**Comment by jonparrott** [comment]
@dhermes I'm not sure what you're asking for?

**Comment by pferate** [comment]
I don't see any support for branches or partials in [coveralls.io](https://coveralls.io), which is kind of surprising.  While I was looking around, I came across [codecov.io](https://codecov.io), which does have support for branches and partials.

**Comment by pferate** [comment]
@dhermes, `tox -e cover` will still fail on partial hits.  We could add that to Travis as well.

**Comment by dhermes** [comment]
@pferate Thanks for digging. @jonparrott and I just chatted in a Hangout about it so I filed #617 for him. We tried codecov.io in `gcloud-python` and didn't have great luck.

**Pull request merged**
