### PR TITLE
Release 1.5.3.

### PR DESCRIPTION
**Pull request by dhermes**

### CODE REVIEW

**Comment by dhermes** [comment]
Ran from

```
$ git log -1 --pretty=%H  # What is HEAD at time of doing "log"
9bd85220faf18349fd4ba0d4a02a1588bcf0f1f6
```

to check PRs since

```
$ git log v1.5.2..HEAD \
> | grep 'Merge pull request ' \
> | awk -F ' ' '{print $4}' \
> | sort
```

yields

#332
#334
#337
#346
#350
#353
#355
#356
#362
#363
#369
#370
#371
#372
#374
#375
#376
#378
#379
#380
#382
#383
#385
#389

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle Here is the summary of the PRs since the last release

----

- #332 - Add Django util With decorator and views (also #383)
- #337 - Avoid OAuth2Credentials `id_token` going out of sync
  after a token refresh.
- Moving many packages to `contrib` sub-package (#346, #353, #370, #375, #376, #382)
- #372 - Add `token_expiry` to `devshell` credentials
- #379 - Move `Storage` locking into a base class
- #380 - Adding dictionary storage
- #385 - Add `to_json`/`from_json` methods to all `Credentials` classes
- Bugfix: Fall back to read-only credentials on EACCES errors (#389)

Project Admin: #334 (new logo), #350 (better error for failed file open), #355 (separating file/multistore_file tests), #356 (improved unit test line coverage), #362 (unpinning tox version in script), #363 (fixing broken test config), #369 (update language in README), #371 (factor out usage of utcnow() in client), #374 (more mocks in implicit environ tests), #378 (Removing keyring testing from py26 testing)

----

Care to craft it into valid notes?

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle The move of many modules to the `contrib` sub-package probably dictates we upgrade to `2.0.0`.

Maybe we should hold off on doing this until #211 is resolved?

**Comment by nathanielmanistaatgoogle** [comment]
Phooey; that thought passed through my mind as we spoke today and then escaped before I gave it voice.

Happy to hold off. If we don't, we probably wind up with some intermediate release that gets barely any use and isn't worth the effort that went into it.

**Comment by dhermes** [comment]
OK. Close this PR then?

**Pull request closed without merging**
