### PR TITLE
Replacing now() with utcnow() in device info code.

### PR DESCRIPTION
**Pull request by dhermes**
This change was discussed in #485.

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
Commit looks good; merge when test results land.

**Comment by dhermes** [comment]
So we aren't worried about breakage?

**Comment by nathanielmanistaatgoogle** [comment]
I'm a little worried, but not as much as I would be had the library ever documented the attribute as being in local time.

Do we feel that the value is worth the cost?

Should this be put on ice and rolled into whatever it is that motivates a more dramatic breaking change?

**Comment by dhermes** [comment]
I don't mind if it gets put on ice but have no desire to be in charge of 

- Keeping track of when it is appropriate to merge this
- Keeping this PR up to date with the library as it gets updated

**Comment by jonparrott** [comment]
I'm in favor of merging this to release with 2.1.0

**Pull request merged**
