### PR TITLE
Adding system tests to make sure token exchange works as expected.

### LINKED ISSUE #127: Add regression / integration tests for merges to master
This is to prevent issues like #125 where unit tests give false sense of working code.

ISTM we'd want the following

- [ ] Python2 / Python3 - Mint a P12 Service Account access token and make a simple request
- [ ] Python2 / Python3 - Mint a JSON Key Service Account access token and make a simple request
- [ ] Python2 / Python3 - Refresh a user OAuth 2.0 token and make a simple request
- [ ] Python2 / Python3 - Mint a user OAuth 2.0 token (not possible on Travis / without human interaction)
- [ ] Python2 / Python3 - Mint a GAE / GCE Service Account access token (not possible on Travis)

### PR DESCRIPTION
**Pull request by dhermes**
Fixes #127

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
I'm going to need some more hand-holding on this - please file an issue so that we can have separate conversations about (a) the particular problem that needs to be solved and (2) the particular solution being proposed for the problem.

Also let's look at breaking up the content of the pull request. A CONTRIBUTING.md file is a great idea but most of its content has nothing to do with the rest of this code - can we separate it out into its own contribution?

How necessary is it to use an unreleased version of https://github.com/jcgregorio/httplib2? Has anyone actually asked @jcgregorio when the next release will be, or to cut a new release that includes the fix?

**Comment by dhermes** [comment]
RE: "How necessary is it to use an unreleased version of `httplib2`

By removing it

```diff
diff --git a/tox.ini b/tox.ini
index d55d91d..578e3b5 100644
--- a/tox.ini
+++ b/tox.ini
@@ -88,9 +88,5 @@ basepython =
 commands =
     {toxinidir}/scripts/run_system_tests.sh
 deps =
-    # Use a development checkout of httplib2 until a release is made
-    # incorporating https://github.com/jcgregorio/httplib2/pull/291
-    # and https://github.com/jcgregorio/httplib2/pull/296
-    -egit+https://github.com/jcgregorio/httplib2.git#egg=httplib2
     pycrypto==2.6
     pyopenssl==0.14
```

and running `tox -e system-tests3` (notice the `recreate` below), `oauth2client` just doesn't work

```
$ tox -e system-tests3
GLOB sdist-make: /home/dhermes/google_contracting/oauth2client/setup.py
system-tests3 recreate: /home/dhermes/google_contracting/oauth2client/.tox/system-tests3
system-tests3 installdeps: pycrypto==2.6, pyopenssl==0.14
system-tests3 inst: /home/dhermes/google_contracting/oauth2client/.tox/dist/oauth2client-1.4.7.zip
system-tests3 runtests: PYTHONHASHSEED='1755257755'
system-tests3 runtests: commands[0] | /home/dhermes/google_contracting/oauth2client/scripts/run_system_tests.sh


# If we're on Travis, we need to set up the environment.
...
# Run the system tests for each tested package.
python scripts/run_system_tests.py
Traceback (most recent call last):
  File "scripts/run_system_tests.py", line 107, in <module>
    main()
  File "scripts/run_system_tests.py", line 100, in main
    _require_environ()
  File "scripts/run_system_tests.py", line 32, in _require_environ
    'OAUTH2CLIENT_TEST_USER_KEY_EMAIL')
OSError: ('Expected environment variables to be set:', 'OAUTH2CLIENT_TEST_JSON_KEY_PATH', 'OAUTH2CLIENT_TEST_P12_KEY_PATH', 'OAUTH2CLIENT_TEST_P12_KEY_EMAIL', 'OAUTH2CLIENT_TEST_USER_KEY_PATH', 'OAUTH2CLIENT_TEST_USER_KEY_EMAIL')
ERROR: InvocationError: '/home/dhermes/google_contracting/oauth2client/scripts/run_system_tests.sh'
___________________________________________________________________ summary ____________________________________________________________________
ERROR:   system-tests3: commands failed
```

I [asked][1] @jcgregorio last week about cutting a release and have yet to hear back.

----

I'll send a PR with the base of `CONTRIBUTING.md` without the system tests section and then can rebase this on top of it.

The changes to `tests/data/gcloud/application_default_credentials_authorized_user.json` can also be peeled off (I wanted this to resemble an actual `application_default_credentials.json` file that the `gcloud` CLI would create, via this library.)

----

Issue #127 already exists to cover (a), and I think it also covers (2). Let me know what you think about that.

[1]: https://github.com/jcgregorio/httplib2/pull/291#issuecomment-85630992

**Comment by nathanielmanistaatgoogle** [comment]
You're absolutely right that #127 is the relevant issue for this change; sorry to have let it slip out of my mind.

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle I have rebased on top of #155 and #156. I split this PR into two commits to make the barrier clear between the tests themselves and the Travis config.

----

The second commit is a dummy / stand-in and should not be accepted in it's current state. Remaining work to be done:

1.  Create a dedicated Cloud Console account for Travis system tests.
1.  Create a service account and download a JSON key.
1.  Download a P12 key for that account (or create a new one).
1.  Create a JSON key for user credentials (can be as simple as copying `~/.config/gcloud/application_default_credentials.json`)
1.  Sign in with the `travis` CLI tool. (See [reference][1])
1.  Define and export the following environment variables:

    ```bash
    export OAUTH2CLIENT_TEST_JSON_KEY_PATH="tests/data/key.json"
    export OAUTH2CLIENT_TEST_P12_KEY_PATH="tests/data/key.p12"
    # Account from svc. account P12 key
    export OAUTH2CLIENT_TEST_P12_KEY_EMAIL="foo@developer.gserviceaccount.com"
    export OAUTH2CLIENT_TEST_USER_KEY_PATH="tests/data/user-key.json"
    # Account from user JSON key
    export OAUTH2CLIENT_TEST_USER_KEY_EMAIL="foo@gmail.com"
    ```

1.  Set the Travis environment variables:

    ```bash
    travis env set GH_OWNER "${GH_OWNER}" --repo "${GH_OWNER}/${GH_PROJECT_NAME}"
    travis env set OAUTH2CLIENT_TEST_JSON_KEY_PATH \
        "${OAUTH2CLIENT_TEST_JSON_KEY_PATH}" --repo "google/oauth2client"
    travis env set OAUTH2CLIENT_TEST_P12_KEY_PATH \
        "${OAUTH2CLIENT_TEST_P12_KEY_PATH}" --repo "google/oauth2client"
    travis env set OAUTH2CLIENT_TEST_P12_KEY_EMAIL \
        "${OAUTH2CLIENT_TEST_P12_KEY_EMAIL}" --repo "google/oauth2client"
    travis env set OAUTH2CLIENT_TEST_USER_KEY_PATH \
        "${OAUTH2CLIENT_TEST_USER_KEY_PATH}" --repo "google/oauth2client"
    travis env set OAUTH2CLIENT_TEST_USER_KEY_EMAIL \
        "${OAUTH2CLIENT_TEST_USER_KEY_EMAIL}" --repo "google/oauth2client"
    ```

1.  [Encrypt][2] the key files against Travis

    ```bash
    travis encrypt-file tests/data/key.json
    travis encrypt-file tests/data/key.p12
    travis encrypt-file tests/data/user-key.json
    ```

    This will create the files `key.json.enc`, `key.p12.enc` and `user-key.json.enc` in the `tests/data/` directory. These are the files that need to be committed. Make sure to take note of the key printed in the `travis` output, e.g. `$encrypted_0a6446eb3ae3_key`. This value will be used in `scripts/run_system_tests.sh` to decrypt.

1.  Log out of Travis (if you want):

    ```bash
    travis logout
    ```

[1]: https://github.com/GoogleCloudPlatform/gcloud-python-wheels#installation-and-set-up
[2]: http://docs.travis-ci.com/user/encrypting-files/

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle Any blockers here?

**Comment by dhermes** [comment]
I just updated this PR to incorporate the new release of `httplib2` (thanks to @jcgregorio!!). (I folded it into the first commit.)

This will also mark the first time this library works with Python 3.

**Pull request merged**
