### PR TITLE
Import clean up

### PR DESCRIPTION
**Pull request by pferate**
- Treat `tests` as part of the local package (for import order)
- Import modules instead of objects (some slipped by since this was cleaned up previously)

### CODE REVIEW

**Comment by jonparrott** [comment]
lgtm. I don't know why django-related code always looks so gross to me.

**Comment by jonparrott** [comment]
(waiting for the test god to merge)

**Comment by pferate** [comment]
Flask > Django?

**Comment by jonparrott** [comment]
> Flask > Django?

At least to me. I've never been much of a fan of Django (though I love their community!)

**Pull request merged**
