### PR TITLE
Releasing 1.5.0.

### PR DESCRIPTION
**Pull request by dhermes**
/cc @nathanielmanistaatgoogle @jonparrott @craigcitro 

(Working out changelog still, will update PR once done)

### CODE REVIEW

**Comment by dhermes** [comment]
```bash
$ git log -1 --pretty=%H  # What is HEAD at time of doing "log"
6e3c0c58f5a3ba18dc69bce9c49a975738c46c74
$ git log v1.4.12..HEAD \
> | grep 'Merge pull request ' \
> | awk -F ' ' '{print $4}' \
> | sort
```

yields

#203
#214
#215
#217
#219
#220
#221
#222
#226
#230
#232
#233
#234
#235
#236
#237
#238
#243
#244
#245
#246
#247
#250
#258
#259
#260
#263
#264
#265
#267
#269
#272
#273
#275
#276
#278
#279
#280
#281
#282
#283
#284
#285
#287
#288
#291

**Comment by dhermes** [comment]
OK I synthesized all the PRs into short snippets. I've gotta commute now, can someone (@nathanielmanistaatgoogle probably)  fix these up into something readable and then I'll put them in the CHANGELOG?

#203 - Fix (more like clarify) bytes/string handling in crypto methods.
#214 - Admin
#215 - Admin (factoring out conditionally defines classes / functions)
#217 - Replacing webapp with webapp2 in oauth2client.appengine
#219 - Added optional 'state' parameter to step1_get_authorize_url.
#220 - Admin (gitignore)
#221 - Admin (mock pinning for broken tests)
#222 - Docs for #219
#226 - Flask 3LO helper (@jonparrott may have a lot to say)
#230 - Track scopes used on credentials objects (pretty great)
#232 - Admin (LICENSE)
#233 - Admin (Using correct name for PyPI / conda)
#234 - Admin (autodoc for flask_util)
#235 - Admin (favicon for docs)
#236 - Admin (whitespace)
#237 - Moving docs to readthedocs.org (sort of Admin, but notable)
#238 - Admin (moved contrib in docs, later removed)
#243 - Admin (fixing "Exceptions" -> "Raises" in docstrings)
#244 - See #238 (removing contrib from docs, just in repo now)
#245 - Admin (dead tox env)
#246 - Admin (tweak toc in docs)
#247 - Admin (dead lines in tox config)
#250 - Unifying conversion to bytes (see #203 too).
#258 - Admin (updating coveralls badge)
#259 - Admin (autodoc adding a flag)
#260 - Admin (making tox -e docs fail if there are undocumented modules)
#263 - Admin (ignore libgmp in tox -e pypy, so that it can build on all systems)
#264 - Admin (temporary pypy2.6 hack for Travis, to support PyCrypto)
#265 - Admin (pypy tips in docs/contrib, see #264)
#267 - Admin (remove hack for importing OpenSSL)
#269 - Admin (See #221, fixing old mock usage)
#272 - Unifying conversion **from** bytes (see #250).
#273 - Wrapping up Flask 3LO. See #226.
#275 - Admin (GAE tests on Travis)
#276 - Admin (PEP8 code)
#278 - Admin (100% coverage: clientsecrets)
#279 - Admin (100% coverage: keyring_storage)
#280 - Admin (100% coverage: gce)
#281 - Admin (100% coverage: xsrfutil)
#282 - Admin (100% coverage: flask_util)
#283 - Admin (htmlcov/ in gitignore)
#284 - Admin (100% coverage: devshell)
#285 - Removing old_run module. Was deprecated July 2, 2013. May cause some breakage.
#287 - Admin (putting GAE tests in coverage report)
#288 - Admin (removing test_import.py)
#291 - Admin (Renaming test_oauth2client.py as test_client.py.)

**Comment by jonparrott** [comment]
For #226 and #273:

> Added flask_util module that provides a Flask extension to aid with using OAuth2 web server flow. This provides the same functionality as the appengine/webapp2 OAuth2Decorator, but will work with any Flask application regardless of hosting environment.

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle I'm looking for your guidance on which `Admin` PRs are worth mentioning in a release and which are not.

**Comment by nathanielmanistaatgoogle** [comment]
I'm happy to do it but I'm not going to get to this until Saturday afternoon at the earliest. Does that make too much trouble?

**Comment by dhermes** [comment]
Not for me. @jonparrott Is timing an issue for you?

**Comment by jonparrott** [comment]
Sometime in the next two weeks works for me.

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle do you have some time to go through and decide which "Admin" PRs are worth mentioning in a release and which are not?

----

Updating at 19abb4d0fb3a49602e23f654cde284fb5b9c3ec3

#290 - Admin (100% coverage: crypt)
#293 - Avoid proxies when querying for GCE metadata (to check if running on GCE), Fixes #114

**Comment by nathanielmanistaatgoogle** [comment]
I intend to find time for this later this afternoon or sometime tomorrow - thank you for your patience. :-)

**Comment by nathanielmanistaatgoogle** [comment]
#219 and #222 get one line in the release notes as they represent one logical semantic change to the library.

#237, #238, and #244 get one line as they too are fellow-travelers.

#226 and #272 share one note.

Don't include any of the admin changes (#265, #267, #276, #287, or any of the others). I'm enormously grateful for the improvements but release notes are for users of the library. Documentation improvements are expected to be happening all the time and don't require any consequent changes to the code of applications using the library and the library's tests are out of the picture entirely (how silly would it be to require users to run the test suite before writing code depending on oauth2client?).

Thank you for the release and for your patience awaiting my comments. :-)

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle PTAL. I updated `CHANGELOG.md` to incorporate this.

You can view it rendered at:
https://github.com/dhermes/oauth2client/blob/release-1.5.0/CHANGELOG.md

On the release the `#` will actually link out.

**Comment by dhermes** [comment]
**Side question**: Shall we use `1.4.12` or `v1.4.12` as the tag name?

The current tags are

```bash
$ git tag
v1.3
v1.3.1
v1.3.2
v1.4
v1.4.1
v1.4.10
v1.4.11
v1.4.12
v1.4.2
v1.4.3
v1.4.4
v1.4.5
v1.4.6
v1.4.7
v1.4.8
v1.4.9
```

Notice that https://readthedocs.org/projects/oauth2client/versions/ has all the `v`'s as well, so if we wanted them to show up on RTD (e.g. http://gcloud-python.readthedocs.org/en/0.7.1/) then the links would include the `v`.

**Comment by nathanielmanistaatgoogle** [comment]
"v" is fine; it's consistent with what the codebase has done to this point and I don't think it's going to scare anyone off.

Looks good; ship it. :-)

**Comment by dhermes** [comment]
After the build for this merge (https://travis-ci.org/google/oauth2client/builds/78612931) finishes, I'll push the tag and then (fingers crossed) Travis will push to PyPI.

**Comment by dhermes** [comment]
OK. Tag pushed and building:
https://travis-ci.org/google/oauth2client/builds/78613327

**Comment by dhermes** [comment]
w00t

New version pushed: https://pypi.python.org/pypi/oauth2client/1.5.0

**Comment by jonparrott** [comment]
Bravo! Thanks everyone.

**Pull request merged**
