### PR TITLE
Django 2.0 support

### PR DESCRIPTION
**Pull request by pauloxnet**
Added support for Django 2.0 with minimum number of code changes and with backward compatibility.

### CODE REVIEW

**Comment by pauloxnet** [comment]
I signed it!

**Comment by jonparrott** [comment]
Thank you for putting in the effort to put this together, @pauloxnet. Unfortunately, this library is deprecated and we won't be accepting any new changes or pull requests.

**Comment by ashwin31** [comment]
if it's deprecated, @jonparrott do you suggest any alternatives for oauth2client?
and please update deprecated message in readme file.

**Comment by ashwin31** [comment]
@jonparrott can we fork it and enhance further?

**Comment by jonparrott** [comment]
The replacement is [google-auth](http://google-auth.readthedocs.io/en/latest/). You're always welcome to fork, it is open-source. :)

**Comment by ashwin31** [comment]
Thank you @jonparrott

**Pull request closed without merging**
