### PR TITLE
Moving locking logic into storage base class.

### PR DESCRIPTION
**Pull request by theacodes**

### CODE REVIEW

**Comment by jonparrott** [comment]
> Coverage decreased (-0.0009%) to 94.45%

ಠ_ಠ

**Comment by dhermes** [comment]
This LGTM. Coverage drop doesn't seem to be an issue looking at the coveralls report.

**Comment by dhermes** [comment]
FWIW, comparing `(a + line_change) / (b + line_change)` to `a / b` will no longer be an issue once `a = b` (i.e. 100% coverage, go #212!)

**Comment by jonparrott** [comment]
Cool. @nathanielmanistaatgoogle care to take a look?

**Pull request merged**
