### PR TITLE
Automating release via Travis.

### LINKED ISSUE #213: Allow Travis to auto-release
See #208 for a discussion about release.

See https://github.com/GoogleCloudPlatform/gcloud-python/blob/bb25b9e924c12c648c3b5ac50d5bdc18409b2a5a/.travis.yml#L24-L33 for an example and http://docs.travis-ci.com/user/deployment/pypi/ for docs.

### PR DESCRIPTION
**Pull request by dhermes**
Fixes #213.

@craigcitro or @nathanielmanistaatgoogle we need a real PyPI account for pushing to this repo from Travis or we could just use one of yours and just encrypt it with the Travis command line tool:

```
travis encrypt PW_GOES_HERE
```

/cc @pcostell @eamonnmcmanus

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
This needs to be reformed following the merge of #216, right?

**Comment by dhermes** [comment]
Yup. Version doesn't need to be cut anymore (two people at Google needed a release).

Now it's just the discussion, do we want to use an existing PyPI account and encrypt to password (a la https://github.com/GoogleCloudPlatform/gcloud-python/blob/583d1cef41b7266994371a6fee546e9f079c382e/.travis.yml#L24-L33) or make a new account or disallow Travis from making releases.

**Comment by dhermes** [comment]
Shall we discuss? Do we want to 

- use an existing PyPI account and encrypt the password
- make a new PyPI account to do the same
- disallow Travis from making releases.

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle Ping, can we discuss the three options listed above?

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle PTAL

**Comment by nathanielmanistaatgoogle** [comment]
Change content LGTM - how do we test this? Can we push to a branch like "1.4.11.test.release.do.not.use" and see that that appears on PyPI or something like that?

**Comment by dhermes** [comment]
We can do an alpha release? Or just wait, it's not really that urgent.

**Comment by dhermes** [comment]
WDYT about an alpha release?

**Comment by nathanielmanistaatgoogle** [comment]
Make it so.

**Comment by dhermes** [comment]
Here is a potential downside of doing this Picard: deleting a version from PyPI is not possible (or maybe just not easy).

**Pull request merged**
