### PR TITLE
Moving CONTRIBUTING out of docs to repository top-level.

### PR DESCRIPTION
**Pull request by dhermes**
Also unifying the old `docs/contributing.rst` with the current contents of `CONTRIBUTING.md`.

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
"... and into repository" sounds like content is coming into source control from outside, which isn't the case. How about "Move CONTRIBUTING to repository top-level"?

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle I also rewrote the original commit to say the same.

While doing it I realized that there is an existing `CONTRIBUTING.md`, which I added in #155!

I suggest we unify these two documents in a follow-up PR. WDYT?

**Comment by dhermes** [comment]
I should also mention that you can see the rendered RST on my branch: https://github.com/dhermes/oauth2client/blob/move-contrib/CONTRIBUTING.rst

**Comment by nathanielmanistaatgoogle** [comment]
Yes; it would be rude of us to maintain CONTRIBUTING.rst and CONTRIBUTING.md as separate documents.

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle I went ahead and merged the two together. Can be seen at: https://github.com/dhermes/oauth2client/blob/move-contrib/CONTRIBUTING.md

**Comment by nathanielmanistaatgoogle** [comment]
LGTM!

**Pull request merged**
