### PR TITLE
Remove reference to old dependency in LICENSE

### PR DESCRIPTION
**Pull request by dhermes**

### CODE REVIEW

**Comment by dhermes** [comment]
@jonparrott Is "removes" or "removing" the right way to say it?

**Comment by jonparrott** [comment]
Remove.

**Comment by dhermes** [comment]
Aw man

**Comment by nathanielmanistaatgoogle** [comment]
Oooh, are we keen on commit message perfection in this pull request? Because [your subject line should be without trailing punctuation](http://chris.beams.io/posts/git-commit/#seven-rules).

**Comment by dhermes** [comment]
OK I'm putting a moratorium on non-change content opinions until I hear if the change LGT someone

**Comment by nathanielmanistaatgoogle** [comment]
The change content looks _fantastic_.

**Comment by dhermes** [comment]
OK got rid of the trailing punctuation. Am I good to merge?

**Comment by nathanielmanistaatgoogle** [comment]
Merge away!

**Pull request merged**
