### PR TITLE
Moving devshell module to contrib.

### PR DESCRIPTION
**Pull request by dhermes**
See discussion in #370 for context.

### CODE REVIEW

**Comment by dhermes** [comment]
I should hold off on doing this until #372 is in.

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle It looks like a brand new release of `keyring` no longer works in Python 2.6:
https://travis-ci.org/google/oauth2client/builds/100392153

Luckily `keyring_storage` is now in `contrib`, so we can make it optional (and leave the `keyring` tests out of the Python 2.6 `tox` environment).

More ammo for #298.

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle I rebased after #372 got it.

**Comment by nathanielmanistaatgoogle** [comment]
Change looks good; merge when tests repass.

**Pull request merged**
