### PR TITLE
Add instructions for updating docs

### LINKED ISSUE #521: Docs for doc gen
The process for generating docs isn't documented anywhere in `CONTRIBUTING.md`

### PR DESCRIPTION
**Pull request by elibixby**
Fixes #521

### CODE REVIEW

**Comment by dhermes** [comment]
`tox -e docs` is the "correct" / "endorsed" way to build docs

The GAE SDK dependency is a nagging issue that @jonparrott was tackling in a more generic way

**Comment by jonparrott** [comment]
We can use `gcp-repo-tools` like python-docs-samples: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/nox.py#L87

**Comment by dhermes** [comment]
:+1: I didn't realize you had reached a stable state with that

**Comment by elibixby** [comment]
Just FYI, my confusion was that you had to commit after running `tox -e docs` which isn't mentioned anywhere in `CONTRIBUTING.md`

**Comment by dhermes** [comment]
You don't have to commit, you just need to add an RST file documenting new modules. `tox -e docs` nudges in this direction in case the humans forget to add the documentation

**Comment by elibixby** [comment]
You at the very least have to `git add` new files generated by `tox -e docs` which wasn't documented either.... haven't tested `git add`ing without committing.

**Pull request closed without merging**
