### PR TITLE
Release v2.0.0-post1.

### PR DESCRIPTION
**Pull request by dhermes**
/cc @jonparrott

### CODE REVIEW

**Comment by dhermes** [comment]
For posterity

```
$ git log -1 --pretty=%H
0c7996099f9e3d74f7b9a6d32b6f69f44987638a
$ git log v2.0.0..HEAD \
> | grep 'Merge pull request ' \
> | awk -F ' ' '{print $4}' \
> | sort
```
yields

#409
#410
#411
#413
#415
#420

and #409 and #410 were left out of the release notes since they are not user facing.

**Comment by nathanielmanistaatgoogle** [comment]
Looks good; merge when you please.

**Comment by jonparrott** [comment]
Thank you, @dhermes and @nathanielmanistaatgoogle. One crisis solved.

@nathanielmanistaatgoogle we need to get a new release of google-api-client-python out ASAP. It's breaking lots of users.

**Comment by dhermes** [comment]
Just manually pushed https://pypi.python.org/pypi/oauth2client/2.0.0.post1 since Travis won't get there for another million seconds

**Pull request merged**
