### PR TITLE
Making save_to_well_known_file() save with 0600 permission.

### LINKED ISSUE #144: Well known file is created with inapproriate permission
When I run "gcloud auth login", the file ${HOME}/.config/gcloud/application_default_credentials.json is created with a permission 0644, which seems inappropriate in my opinion. I think it should be 0600 or something stricter.

### PR DESCRIPTION
**Pull request by dhermes**
Fixes #144.

H/T to http://stackoverflow.com/a/5624691/1068170 and
       http://stackoverflow.com/a/5337329/1068170

### CODE REVIEW

**Comment by anthmgoogle** [comment]
LGTM.

Do you need someone to pull this request in?

**Comment by dhermes** [comment]
Yes I don't have merge privileges. But the build failed
https://travis-ci.org/google/oauth2client/jobs/55736796

I need to update so that the correct octal syntax is used for Python 3: `0o0600`

**Comment by dhermes** [comment]
@anthmgoogle I just updated the PR with the fix.

Waiting on new build: https://travis-ci.org/google/oauth2client/builds/55836779

**Comment by anthmgoogle** [comment]
There is a manual test step that should be done here also:
1. Take a sample using the get_application_default auth feature to call a Google API.
2. Use the Google Cloud SDK and run gcloud_auth_login and confirm the prompt.
3. Verify that this enables the sample to work. It should pick up the credential file saved gcloud auth login.
4. Patch this change into the copy of this code in the Cloud SDK.
5. Repeat steps 2-3 to verify there is no regression.

**Comment by dhermes** [comment]
Good call! I discovered it doesn't over-write permissions of an existing file. Will update and create a corresponding unit test.

**Comment by dhermes** [comment]
@anthmgoogle I edited the version of `oauth2client.client` in the SDK and confirmed this all works as expected. New unit test and code change in the second commit just pushed.

**Comment by anthmgoogle** [comment]
Revision LGTM.

**Comment by dhermes** [comment]
Great @craigcitro care to merge?

**Comment by nathanielmanistaatgoogle** [comment]
@dhermes Squash commits? It's not clear why there should be two commits for this change; it looks like it's only an artifact of the trajectory this code took through review.

**Comment by dhermes** [comment]
SGTM @nathanielmanistaatgoogle 

I like the way you think! (I try to be the "fewer commits" stickler, but usually get shot down.)

**Pull request merged**
