### PR TITLE
Updating logo

### PR DESCRIPTION
**Pull request by hvardhanx**
https://github.com/google/oauth2client/issues/296

### CODE REVIEW

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle This LGTM

Preview at: https://raw.githubusercontent.com/royalharsh/oauth2client/master/docs/_static/favicon.ico

**Comment by nathanielmanistaatgoogle** [comment]
My apologies for the delay with this. Where did you find the two files introduced in this change?

**Comment by royalharsh** [comment]
Google

**Comment by nathanielmanistaatgoogle** [comment]
I figured. :-P Any particular URLs?

**Comment by royalharsh** [comment]
Don't remember :/

**Pull request merged**
