### PR TITLE
100% coverage for oauth2client.util

### PR DESCRIPTION
**Pull request by theacodes**
Towards #212.

### CODE REVIEW

**Comment by dhermes** [comment]
LGTM pending Travis

**Comment by dhermes** [comment]
Ha. The moment I posted we got b0rken Travis

**Comment by dhermes** [comment]
Score one for non-deterministic dictionary order

**Comment by jonparrott** [comment]
lol for real. Pushed the fix.

**Comment by jonparrott** [comment]
Merging, @nathanielmanistaatgoogle if you have an qualms I'll be happy to send a follow-up PR.

**Comment by dhermes** [comment]
:+1:

**Comment by nathanielmanistaatgoogle** [comment]
One stray wrongfully inserted newline. :-P We can hold off on cleaning that up until we decide to work toward a lint-clean-codebase objective.

**Comment by jonparrott** [comment]
@nathanielmanistaatgoogle fair enough. I think I'm more generous with newlines inside of methods than you are. :)

**Comment by dhermes** [comment]
The spurious newlines are between class defs

**Comment by jonparrott** [comment]
Ah. Well, one more for the linter.

**Pull request merged**
