### PR TITLE
Syntax fixes for fetch_gae_sdk

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
I signed it!

**Comment by dhermes** [comment]
LGTM @nathanielmanistaatgoogle will wait for you to merge

**Comment by jayvdb** [comment]
fwiw, these were found using https://github.com/xZise/flake8-string-format

It has some false positives, but it appears they could be easily worked around by simple changes to a few docstrings in this project, and the array of codes allows checking docstrings to be disabled.

I notice there is no `flake8` or `pep8` section in `tox.ini` at the moment.  I'd be happy to add a flake8 section to tox.ini to document and disable error codes this codebase doesnt 'pass' yet, if interested.

**Comment by dhermes** [comment]
We have a similar set-up in `gcloud-python` and will be turning it on for this project at some point.

For now #212 is the most pressing code quality issue.

**Comment by nathanielmanistaatgoogle** [comment]
Thanks for the contribution!

**Pull request merged**
