### PR TITLE
Update appengine.py

### PR DESCRIPTION
**Pull request by sorensenjs**
Correct typo of oauth2, was oath2. This is a comments only change.

### CODE REVIEW

**Comment by dhermes** [comment]
Thanks. LGTM

**Comment by nathanielmanistaatgoogle** [comment]
I'm not sure if your use of the word "type" is intended or is itself a typo for "typo".

Also please take a look at [these guidelines](http://chris.beams.io/posts/git-commit/#seven-rules) for your commit message - the summary line is supposed to be short, but it shouldn't be so short that it's a tautology.

The content of this change looks great, of course.

**Comment by sorensenjs** [comment]
Hopefully addressed.

**Comment by nathanielmanistaatgoogle** [comment]
I'm not yet seeing a different commit - check that your push went through?

**Comment by sorensenjs** [comment]
Sorry I have no clue what I'm supposed to do from here - I edited the commit message to read:
Correct typo of oauth2, was oath2. This is a comments only change.
but can't figure out what the next step is.

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle Wants you to update your original commit message. Do you have a local `git` checkout of the repo?

If you do you can update the message like so:

```bash
$ git checkout patch-1
$ git commit --amend
$ # Manually edit your commit message
$ git push --force origin patch-1  # This assumes your remote is called origin
```

**Comment by sorensenjs** [comment]
No I just edited directly using the pencil icon.

**Comment by dhermes** [comment]
Yeah I figured that was the case based on the generic name of the branch (`patch-1`).

Your commit message is fine with me, though I also encourage reading the link @nathanielmanistaatgoogle shared for future commit messages that you write.

**Comment by sorensenjs** [comment]
Hopefully that's right. Thanks for the docs, but I don't think I'll be doing this again soon. And, fixing a typo is literally the first example, where it says no further comments are necessary.

**Comment by nathanielmanistaatgoogle** [comment]
Take a look at [the "Commits" tab](https://github.com/google/oauth2client/pull/456/commits) of this pull request - there are three commits there, but I don't think you intended to author more than one?

Does using the pencil icon mean that you don't get full control over what your commit log message will be? That would stink.

**Pull request closed without merging**
