### PR TITLE
Check whether a credential loaded from a store is expired before using it.

### PR DESCRIPTION
**Pull request by mattmoor**

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
What hope is there for test coverage for this change?

**Comment by mattmoor** [comment]
Technically you were already covering it with bad tests. ;-)

I fixed the break and added testing of an actual refresh.

**Comment by mattmoor** [comment]
ping?

**Comment by nathanielmanistaatgoogle** [comment]
Please tweak your commit message to be in accordance with http://chris.beams.io/posts/git-commit/#seven-rules.

Code looks reasonable to me, but @anthmgoogle or @soltanmm, would you mind being a second pair of eyes and also reviewing?

**Comment by mattmoor** [comment]
Should be done.

**Comment by nathanielmanistaatgoogle** [comment]
Commit message is much better; thanks.

**Comment by thobrla** [comment]
Created a updated pull request based on this logic at https://github.com/google/oauth2client/pull/173 that also covers the case where the token in the store is about to expire.

**Comment by craigcitro** [comment]
this was actually included in #173 (i think we needed to mention that in the commit to magically close this?).

**Pull request closed without merging**
