### PR TITLE
Add asserts for HTTP request mocks in test_gce

### PR DESCRIPTION
**Pull request by dhermes**
~~**NOTE**: Uses #598 as diff base.~~

~~**NOTE**: Uses #599 as diff base.~~

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
I've seen many diffs base in my time and [issue 599](https://github.com/google/oauth2client/issues/599) is no diff base.

Needs resolution.

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle I had an off-by-one error. Rebased nonetheless.

**Comment by jonparrott** [comment]
I support this change, but it seems to be failing in travis?

**Comment by nathanielmanistaatgoogle** [comment]
Change content looks fine; poke again when [pull request 598](https://github.com/google/oauth2client/pull/598) is in and tests are passing.

**Comment by dhermes** [comment]
It turns out #602 makes this irrelevant.

**Pull request closed without merging**
