### PR TITLE
Unpinning tox version in install script.

### PR DESCRIPTION
**Pull request by dhermes**
Regressions from tox 2.2.0 were fixed in >=2.3.

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
Completely unpinned dependencies are a project's way of saying "we would like to be broken sometime in the future at a time not of our choosing and with no advance notice". Why not just move the pin forward?

**Comment by dhermes** [comment]
But using someone else's library is a way of saying "we are a part of an open-source eco-system" and by using the latest version is a way of telling our peers "we want to help you kick the tires of your library and are excited about new features you release"

----

In other words, I disagree. I think using the latest version on PyPI allows us to upgrade automatically when it does smoothly and quickly detect breakages when it does not.

**Comment by nathanielmanistaatgoogle** [comment]
Okay.

**Comment by dhermes** [comment]
Haha that was easy :grinning: Thanks for the merge

**Pull request merged**
