### PR TITLE
Try to revoke token with POST when getting a 405

### PR DESCRIPTION
**Pull request by LiraNuna**
The OAuth spec does not specify the HTTP verb explicitly but it does hint that POST is the correct verb.
When using the client library with other OAuth services that implement revocation token via a POST, revoking the token will fail.

This commit adds the ability to re-try the revocation process if we get a 405 with the POST verb.

### CODE REVIEW

**Comment by LiraNuna** [comment]
I signed it!

**Comment by jonparrott** [comment]
Hi @LiraNuna! This change looks good, but you'll need to add another test to cover this so that travis passed.

**Comment by LiraNuna** [comment]
@jonparrott Just noticed the failure as well - I'll get the tests soon.

**Comment by jonparrott** [comment]
Sounds good, just ping me when you're ready.

(Also, small world - I remember you from NDS dev stuff. 😄 )

**Comment by LiraNuna** [comment]
@jonparrott Tests fixed - I had to reshuffle stuff around to get the desired behavior correctly.

**Comment by jonparrott** [comment]
Thanks for the contribution, @LiraNuna!

**Comment by LiraNuna** [comment]
@jonparrott how soon should I expect this to show up on PyPI? I've noticed the current code is a bit different than `3.0.0`

**Comment by jonparrott** [comment]
I'm not sure.

**Pull request merged**
