### PR TITLE
Documented 'state' parameter.

### PR DESCRIPTION
**Pull request by frederikcreemers**
Sorry, forgot to do this in the original PR. If you want me to squash this commit with the one where I actually added the parameter, let me know.

### CODE REVIEW

**Comment by dhermes** [comment]
LGTM

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle We are good to merge here. Just wanted to give you final sign off. (LMK if you are OK with me merging in future.)

**Comment by nathanielmanistaatgoogle** [comment]
@dhermes: Consider yourself fully empowered and trusted to merge in the future. :-)

**Comment by dhermes** [comment]
Thanks!

**Pull request merged**
